set HOST=""
set PORT="443"
set USER=""
set PASS=""
set DEVICE_SECRETKEY=""
set DEVICE_COUNT="2"
set DEVICE_NAME_PREFIX="DeviceFleet"
set UID_KEY="0"

python.exe device_simulator_fleet_automation.py --USE_HOST %HOST% --USE_PORT %PORT% --USE_USERNAME %USER% --USE_PASSWORD %PASS% --USE_DEVICE_SECRETKEY %DEVICE_SECRETKEY% --USE_DEVICE_COUNT %DEVICE_COUNT% --USE_DEVICE_NAMEPREFIX %DEVICE_NAME_PREFIX% --USE_UID_KEY %UID_KEY%
pause

