stages:
  - build
  - deploy

before_script:
  - echo $PATH
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose rm -f
    - docker network prune -f
    - docker-compose -f docker-compose.yml config
    - docker-compose build

deploy:
  stage: deploy
  script:
    - docker-compose up -d

