stages:
  - build
  - deploy

before_script:
  - pwd
  - echo $PATH
  - echo $CONFIG_USE_APIURL
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose rm -f
    - docker network prune -f
    - docker-compose -f docker-compose-mini.yml config
    - docker-compose -f docker-compose-mini.yml build --no-cache

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose-mini.yml up -d

