version: '3.0'
services:
  mongodb:
    build: ./mongodb
    restart: always
    networks:
      - mydockernet
    ports:
      - "27017:27017"
    volumes:
      - "mongodb-data:/data/db"
networks:
  mydockernet:
    driver: bridge
volumes:
  mongodb-data:
    driver: local
