docker stop libpyiotcloud_master_notification_1
docker stop libpyiotcloud_master_nginx_1
docker stop libpyiotcloud_master_webapp_1
docker stop libpyiotcloud_master_restapi_1
docker stop libpyiotcloud_master_history_1
docker stop libpyiotcloud_master_mongodb_1
docker stop libpyiotcloud_master_rabbitmq_1

docker rm libpyiotcloud_master_notification_1
docker rm libpyiotcloud_master_nginx_1
docker rm libpyiotcloud_master_webapp_1
docker rm libpyiotcloud_master_restapi_1
docker rm libpyiotcloud_master_history_1
docker rm libpyiotcloud_master_mongodb_1
docker rm libpyiotcloud_master_rabbitmq_1

docker-compose down
docker-compose rm -f
docker network prune -f

