apiVersion: v1
kind: Secret
metadata:
  name: environment
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 
  AWS_COGNITO_CLIENT_ID: 
  AWS_COGNITO_USERPOOL_ID: 
  AWS_COGNITO_USERPOOL_REGION: 
  AWS_PINPOINT_EMAIL: 
  AWS_PINPOINT_ID: 
  AWS_PINPOINT_REGION: 
  AWS_SECRET_ACCESS_KEY: 
  CONFIG_USE_ECC: 
  PAYPAL_CLIENT_ID: 
  PAYPAL_CLIENT_SECRET: 
  TWILIO_ACCOUNT_SID: 
  TWILIO_AUTH_TOKEN: 
  TWILIO_NUMBER_FROM: 
  NEXMO_KEY: 
  NEXMO_SECRET: 
  CONFIG_USE_EMAIL_MODEL: 
  CONFIG_USE_SMS_MODEL: 
  CONFIG_USE_CERTS: 
  CONFIG_USE_APIURL: 
 