apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: iotnotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotnotification
  template:
    metadata:
      labels:
        app: iotnotification
    spec:
      containers:
        - name: iotnotification
          image: richmondu/iotnotification
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: environment
                key: AWS_ACCESS_KEY_ID
          - name: AWS_PINPOINT_EMAIL
            valueFrom:
              secretKeyRef:
                name: environment
                key: AWS_PINPOINT_EMAIL
          - name: AWS_PINPOINT_ID
            valueFrom:
              secretKeyRef:
                name: environment
                key: AWS_PINPOINT_ID
          - name: AWS_PINPOINT_REGION
            valueFrom:
              secretKeyRef:
                name: environment
                key: AWS_PINPOINT_REGION
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: environment
                key: AWS_SECRET_ACCESS_KEY
          - name: CONFIG_USE_ECC
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_ECC
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              secretKeyRef:
                name: environment
                key: TWILIO_ACCOUNT_SID
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: environment
                key: TWILIO_AUTH_TOKEN
          - name: TWILIO_NUMBER_FROM
            valueFrom:
              secretKeyRef:
                name: environment
                key: TWILIO_NUMBER_FROM
          - name: NEXMO_KEY
            valueFrom:
              secretKeyRef:
                name: environment
                key: NEXMO_KEY
          - name: NEXMO_SECRET
            valueFrom:
              secretKeyRef:
                name: environment
                key: NEXMO_SECRET
          - name: CONFIG_USE_EMAIL_MODEL
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_EMAIL_MODEL
          - name: CONFIG_USE_SMS_MODEL
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_SMS_MODEL
