apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: iotnginx
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
