apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: iotrabbitmq
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 8883
    targetPort: 8883
    nodePort: 30883
    protocol: TCP
  - name: amqp
    port: 5671
    targetPort: 5671
    nodePort: 30671
    protocol: TCP
