apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: iotrabbitmq
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 8883
    targetPort: 8883
    nodePort: 30883
    protocol: TCP
  - name: mgmt
    port: 15672
    targetPort: 15672
    nodePort: 30672
    protocol: TCP
