apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  labels:
    app: iotsensor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotsensor
  template:
    metadata:
      labels:
        app: iotsensor
    spec:
      containers:
        - name: iotsensor
          image: richmondu/iotsensor
          env:
          - name: CONFIG_USE_ECC
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_ECC
          - name: CONFIG_USE_MQTT_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_MQTT_DEFAULT_USER
          - name: CONFIG_USE_MQTT_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_MQTT_DEFAULT_PASS
