apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: iotwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotwebapp
  template:
    metadata:
      labels:
        app: iotwebapp
    spec:
      containers:
        - name: iotwebapp
          image: richmondu/iotwebapp
          ports:
          - containerPort: 8100
          env:
          - name: CONFIG_USE_APIURL
            valueFrom:
              secretKeyRef:
                name: environment
                key: CONFIG_USE_APIURL
