'''
Dispute
braintree.WebhookNotification.Kind.DisputeOpened
braintree.WebhookNotification.Kind.DisputeLost
braintree.WebhookNotification.Kind.DisputeWon
braintree.WebhookNotification.Kind.DisputeAccepted
braintree.WebhookNotification.Kind.DisputeDisputed
braintree.WebhookNotification.Kind.DisputeExpired
'''
